### ISSUE TITLE
Note about S/R Breakouts and Retests

### ISSUE THREAD

**Issue by cyberjunky** [nomad5am/legendary_ta#3]
You cannot use these values to trigger buy or sell because of lagging (center=True)
They are perfectly placed to do but alas...
```
 (qtpylib.crossed_below(dataframe['support_level'], 0))
 (qtpylib.crossed_above(dataframe['resistance_level'], 0))
```

**Comment by just-nilux** [comment]
Yes you are right, of course it shouldn't be like this... so unnecessary. Anyways, it's fixed now :)

**Comment by cyberjunky** [comment]
Thanks, but without the center=True it doesn't seem to work that good, trigger on wrong moments. But I have to check.. i guess it's due to the way the indicator works, is there a Pine clone you use to convert and we can compare with or did you create this one yourself?
